### ISSUE TITLE
Suggestions/QoL/Bugs

### ISSUE THREAD

**Issue by Taxibutle** [akuse-app/Akuse#10]
These are mainly some QoL fixes and such but I think they are necessary.

1: Clicking off the side of the anime box when you open one (or pressing ESC) should close the box rather than requiring you to click the X in the top corner

2: Save audio settings between reboots of the app (currently, if you start a video and change the audio, it will **not** save that audio if you restart the app later, which is a problem with the next suggestion)

3: Syncing doesn't really work. Currently, if you change the status of something, then it _will_ save to Anilist, but the app never refreshes or adds it to your list. This means that you have to restart the app after adding a bunch of stuff to your list to refresh it, leading to the audio issue from before. This **also** includes when you watch something, which will not change the status until you restart the app.

4: If you start watching an anime and click "next episode" but don't get all the way through (or just start the next episode), then the next time you use the app it will start from the next episode after that. For example, if I watch up to episode 3 of X anime and click next episode to the very start of episode 4, when I next click to resume watching (maybe later in the day or another day; NOT the play button, just when clicking to resume in the main menu, check next image) it will go to episode 5. This is both annoying and worse due to the fact there is only a next episode button and no way to go back an episode without going back to the episode list (to my knowledge)
![image](https://github.com/akuse-app/Akuse/assets/25257631/3ae28f75-d786-4ea5-b2f1-8f47ad770d18)

5: A decent bit of the time while launching the app, it will ask to login again. This is especially weird (a bug) since you can click the menu button and literally see that you are logged in and click settings and such (the pic only shows me opening the menu, going into profile shows my account, same with settings). Even more so, once you click on any of the options in that menu you can no longer go back to the login screen, meaning you have to force kill the app with task manager. Sometimes when clicking log in, it will say "Validation fail", but if you simply re-do the captcha then it works.
![image](https://github.com/akuse-app/Akuse/assets/25257631/9423e800-3981-4efe-85d4-d9191c176d09)

6: Would be nice to have an X in the top right corner of the app (not the anime menus for this one) to close the app without needed to use the taskbar (I think you can log-out but I don't think that closes the app).

7: Could be cool to also have a Manga section, but that is a big ask.

8: (bug) CTRL-R kills the app

9: Maybe a "run on start-up" option? Also not sure if it has auto-update or update notifications since it has only the beta versions right now.

10: Maybe an episode counter under the names in the "Continue Watching" section, like "8/24" to represent the red bar numerically.

Everything else in the app works really nicely. Stuff is high quality, doesn't lag or crash, UI looks good for the most part. Sources seem good, even though we can't switch between them. Very sleek.

**Comment by aleganza** [comment]
Thanks for all these suggestions, they mean a lot for the app development. Luckily some of them have already been fixed in the version released a bunch of minutes ago:

1: I thought about that functionality too late, it will surely be added, btw now you can close modal pages by clicking outside.
2: Could be interesting, it will be added.
3: Fixed with v0.1.0.
4: Fixed with v0.1.0 (Now progress is updated when reached the 80% of the episode duration).
5: That is related to AniList, honestly I don't know if the authentication could be improved, but I will surely check the API within the next releases.
6: That was a weird bug. it is now fixed with v0.1.0, now when you close the authentication window, the app quits.
7: I'm afraid I will not implement a Manga section, since the app was born as an Anime streaming service only.
8: I'll surely look into this bug.
9: Auto-updates have just been implemented in v0.1.0, and a "run on start up" option doesn't seem like a bad idea.
10: Added with v0.1.0, now the "Resume" button also displays the current episode number.

**Comment by aleganza** [comment]
Closing this since the app is getting full revamped, so some requested features have been added and other changed.
